# Generated by Django 5.1 on 2024-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('bookimg', models.ImageField(blank=True, null=True, upload_to='file path')),
                ('genres', models.CharField(choices=[('Fiction', 'Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Mythology', 'Mythology')], max_length=130, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='file path')),
            ],
        ),
    ]
